name: JWTAPL CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Install Dyalog APL
        run: |
          DEBFILE=`curl -o - -s https://www.dyalog.com/uploads/php/download.dyalog.com/download.php?file=docker.metafile | awk -v v="19.0" '$0~v && /deb/ {print $3}'`
          curl -o /tmp/dyalog.deb ${DEBFILE}
          sudo apt install -y /tmp/dyalog.deb
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.X'
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Activate Tatin and Cider
        run: "${GITHUB_WORKSPACE}/.github/workflows/activate.sh"
      - name: Run Tests
        run: "${GITHUB_WORKSPACE}/.github/workflows/test.sh"
      